search/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls import (
handler400, handler403, handler404, handler500
)


handler404 = 'search.views.handler404'
handler500 = 'search.views.handler500'


app_name = 'search'

urlpatterns = [
    url('articles/', views.ArticlesView.as_view(), name='articles'),
    url('help/', views.HelpView.as_view(), name='help'),
    url(r'^advance-search/$', views.AdvanceSearch.as_view(), name='advance-search'),
    url(r'^advance/results/', views.AdvanceSearch.as_view(), name='advance-results'),
    url('results/', views.ResultsView.as_view(), name='results'),
    url('manage/articles/', views.ArticlesManageView.as_view(), name='articles-manage'),
    url('manage/find/', views.FindFilesView.as_view(), name='find-files'),
    url('manage/update/', views.UpdateFilesView.as_view(), name='update-files'),
    url('manage/postingfile/', views.PostingfileView.as_view(), name='postingfile'),
    url('manage/change/', views.ChangeFilesView.as_view(), name='change-files'),
    url('manage/delete/', views.DeleteFilesView.as_view(), name='delete-files'),
    url('manage/stoplist/view/', views.StoplistView.as_view(), name='stoplist-view'),
    url('manage/stoplist/add/', views.AddToStoplistView.as_view(), name='stoplist-words'),
    url('manage/files/', views.ManageFilesView.as_view(), name='manage-files'),
    url('manage/stoplist/', views.ManageStoplistView.as_view(), name='manage-stoplist'),
    url('manage/settings/find/', views.SettingsView.as_view(), name='manage-settings'),
    url('manage/settings/', views.FindFilesView.as_view(), name='manage-new-files'),
    url('manage/', views.ManageView.as_view(), name='manage'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)$', views.DetailView.as_view(), name='details'),

    # url(r'^submit', views.AddFileView.as_view(), name='addFilesSubmit'),
]

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    # url(r'^$', include('search.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include('search.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/views/AdvanceSearch.py
from django.views.generic import TemplateView
from search.models import Article
from .ResultsView import ResultsView
import re
from django.shortcuts import render


class AdvanceSearch(TemplateView):
    template_name = 'search/advance.html'
    model = Article
    first_not_flag, second_not_flag = False, False

    def post(self, request):
        data = str(request.POST.get('find', ""))
        first_start, second_start, second_end = -1, -1, -1
        sound = request.POST.get('sound', 'no')
        sound = False if sound == 'no' else True
        results = []
        wordlist = []
        error = ""
        first_result_flag = True
        ResultsView.searches.insert(0, data)
        data = data.lower()

        for place in range(len(data)):
            if data[place] == "^" and first_start == -1:
                self.first_not_flag = True
            elif data[place] == "^" and second_start == -1:
                self.second_not_flag = True
            elif data[place] == "(":
                first_start = place
            elif data[place] == "[":
                second_start = place
            elif data[place] == ")":
                if second_end == -1 and second_start != -1:
                    error = "Error. No closing brackets to [."
                elif first_start == -1:
                    error = "Error. No opening bracket for )."
                else:
                    articles, words = self.parse_brackets(data[first_start+1:place], sound, first_start, second_start,
                                                          second_end)
                    wordlist = set(list(wordlist) + list(words))
                    if first_result_flag:
                        results = articles
                        first_result_flag = False
                    else:
                        if second_start > -1:
                            operator = self.find_operator(data, second_start, second_end)
                        else:
                            operator = self.find_operator(data, first_start, place)
                        results = self.filter_articles(results, articles, operator)
                    first_start = -1
                    self.first_not_flag = False
                    second_start, second_end = -1, -1
            elif data[place] == "]":
                if second_start == -1:
                    error = "No opening bracket for ]."
                second_end = place
                articles, words = self.parse_brackets(data[second_start:place], sound, first_start, second_start)
                if first_result_flag:
                    results = articles
                    first_result_flag = False
                else:
                    wordlist = set(list(wordlist) + list(words))
                    operator = self.find_operator(data, second_start, second_end)
                    results = self.filter_articles(results, articles, operator)
                self.second_not_flag = False

        if first_result_flag:
            results, words = self.parse_brackets(data, sound, 0)
            wordlist = set(list(wordlist) + list(words))

        words = [word[:len(word)-1] for word in wordlist if word[len(word)-1] == "*"]
        wordlist = list(wordlist) + words

        return render(request, 'search/results.html', {"results": results, "error": error, "keywords": wordlist,
                                                       "searcher": ResultsView.searches,
                                                       "search": data})

    def clean_string(str):
        str = str.replace("^", "")
        str = str.replace("[", "")
        str = str.replace("]", "")
        str = str.replace("(", "")
        str = str.replace(")", "")
        return str

    def parse_brackets(self, data, sound, first_start, second_start=-1, second_end=-1):

        if second_end > -1:
            data = data[:second_start] + data[second_end + 1:]
        data = AdvanceSearch.clean_string(data)

        words = re.split("&&|&|\|\|", data)

        if data.find("&&") > -1:
            return self.get_and_articles(words, sound, first_start, second_start)
        elif data.find("&") > -1:
            return self.get_easy_and_articles(words, sound, first_start, second_start)
        else:
            return self.get_or_articles(words, sound, first_start, second_start)

    def get_and_articles(self, wordlist, sound, first_start, second_start):
        # delete empty strings
        wordlist = [word for word in wordlist if word]
        if (second_start > -1 and self.second_not_flag) or \
                (first_start > -1 and self.first_not_flag):
            return ResultsView.not_statement(wordlist, "and", sound), wordlist

        return ResultsView.and_statement(wordlist, False, sound), wordlist

    def get_easy_and_articles(self, wordlist, sound, first_start, second_start):
        # delete empty strings
        wordlist = [word for word in wordlist if word]
        if (second_start > -1 and self.second_not_flag) or \
                (first_start > -1 and self.first_not_flag):
            return ResultsView.not_statement(wordlist, "easy-and", sound), wordlist

        return ResultsView.easy_and_statement(wordlist, False, sound), wordlist

    def get_or_articles(self, wordlist, sound, first_start, second_start):
        # delete empty strings
        wordlist = [word for word in wordlist if word]

        if (second_start > -1 and self.second_not_flag) or \
                (first_start > -1 and self.first_not_flag):
            return ResultsView.not_statement(wordlist, "or", sound), wordlist
        return ResultsView.or_statement(wordlist, False, sound), wordlist

    def find_operator(self, data, start, end):
        if data[start-1] == '^':
            start -= 1
        if (start > 2 and data[start-1] == '&' and data[start-2] == '&') or\
                (end+2 < len(data) and data[end+1] == '&' and data[end+2]):
            return "and"
        elif (start > 1 and data[start-1] == '&') or\
                (end+1 < len(data) and data[end+1] == '&'):
            return "easy-and"
        elif (start > 2 and data[start-1] == '|' and data[start-2] == '|') or \
                (end+2 < len(data) and data[end+1] == '|' and data[end+2] == '|'):
            return "or"

    def filter_articles(self, results, articles, operator):
        final_results = []
        if operator == "and":
            final_results = set(results) & set(articles)
        elif operator == "or":
            final_results = set(results) - set(articles)
        elif operator == "easy-and":
            max_list = results if len(results) >= len(articles) else articles
            min_list = results if len(results) < len(articles) else articles

            if len(set(max_list) & set(min_list)) < 0.6 * len(max_list):
                final_results = set(max_list) & set(min_list)
        return final_results

search/views/ArticlesView.py
from ..models import Article
from django.views import generic


class ArticlesView(generic.ListView):
    model = Article
    template_name = 'search/article_list.html'
    context_object_name = 'all_articles'

    def get_context_data(self, **kwargs):
        context = super(ArticlesView, self).get_context_data(**kwargs)
        context['error_msg'] = "No articles was found"
        return context

    def get_queryset(self):
        return Article.objects.all().exclude(hide=True)


class ArticlesManageView(generic.ListView):
    model = Article
    template_name = 'search/article_list.html'
    context_object_name = 'all_articles'

    def get_context_data(self, **kwargs):
        context = super(ArticlesManageView, self).get_context_data(**kwargs)
        context['error_msg'] = "No articles was found"
        return context

    def get_queryset(self):
        print("ok")
        return Article.objects.all()

search/views/DetailView.py
from ..models import Article
from django.views import generic


class DetailView(generic.DetailView):
    model = Article
    template_name = 'search/detail.html'

search/views/FindFilesView.py
from urllib.parse import urlparse
import re
from django.core.exceptions import ObjectDoesNotExist
import requests
from django.shortcuts import render
from bs4 import BeautifulSoup
from search.models import Article, Word, Postingfile as Pfile
from django.views import generic
import os
from soundex import getInstance
from PyDictionary import PyDictionary

# coding: utf-8


class FindFilesView(generic.ListView):
    model = Article
    context_object_name = 'all_articles'
    url = 'http://shakespeare.mit.edu/Poetry/sonnets.html'
    amount = 4

    def get_context_data(self, **kwargs):
        context = super(FindFilesView, self).get_context_data(**kwargs)
        articles = self.crawling_url(self.url, self.amount)

        if not articles:
            context['error_msg'] = "No new articles was found"
        context['all_articles'] = articles
        return context

    def post(self, request):
        url = request.POST.get('url', self.url)
        narticles = request.POST.get("narticles", "4")
        narticles = int(narticles)
        self.url = url
        self.amount = narticles
        articles = self.crawling_url(url, narticles)
        return render(request, "search/results.html", {'results': articles})

    def crawling_url(self, url, article_number):
        split_url = url.rsplit('/', 1)
        url_domain = split_url[0]
        r = requests.get(url)
        html_content = r.text
        soup = BeautifulSoup(html_content)
        links = soup.find_all('a', href=True)
        hrefs = []
        for a in links:
            o = urlparse(a["href"])
            if not o.scheme:
                if a["href"] and not a["href"][0] == '/':
                    a["href"] = url_domain + '/' + a["href"]
                else:
                    a["href"] = url_domain + a["href"]
            if urlparse(a["href"]).netloc != urlparse(url_domain).netloc:
                continue
            hrefs.append(a["href"])
        hrefs = set(hrefs[:article_number])

        articles = FindFilesView.save_articles(hrefs)
        return articles

    def save_articles(links):
        articles = list()
        for link in links:
            if not FindFilesView.check_if_url_exists(link):
                r = requests.get(link)
                if r.status_code == 200:
                    html_content = r.content
                    soup = BeautifulSoup(html_content)
                    # clear script and style elements
                    for script in soup(["script", "style"]):
                        script.extract()

                    title = soup.title.string
                    text = soup.body.get_text()
                    filename = 'media/' + title + '.txt'
                    file = open(filename, 'w')
                    file.write(text)
                    file.close()

                    file = open(filename, 'r')
                    text = file.read()
                    # break into lines and remove leading and trailing space on each
                    lines = (line.strip() for line in text.splitlines())
                    # break multi-headlines into a line each
                    chunks = (phrase.strip() for line in lines for phrase in line.split("  "))
                    # drop blank lines
                    text = '\n'.join(chunk for chunk in chunks if chunk)

                    regex = re.compile(r'[\n\r\t]')
                    text = text.rstrip()
                    text = regex.sub(' ', text)

                    summary = text[:300]
                    article = Article(title=title, summary=summary, url=link)
                    article.save()
                    articles.append(article)
                    article = Article.objects.get(pk=article.pk)
                    FindFilesView.save_words(article, text)
                    file.close()
                    os.remove(filename)

        return articles

    def save_words(article, text):
        word_list = re.findall(r"[\w']+", text)
        word_list = [word.lower() for word in word_list]
        word_list.sort()

        for word in word_list:
            try:
                new_word = Word.objects.get(data=word, article=article)
                new_word.amount += 1
                new_word.save()
            except (ObjectDoesNotExist, Word.DoesNotExist):
                new_word = Word()
                new_word.article = article
                new_word.data = word
                new_word.amount = 1
                soundex = getInstance().soundex(word)
                new_word.soundex = soundex
                new_word.save()
            finally:
                try:
                    pfile_word = Pfile.objects.get(data=word)
                    pfile_word.words.add(new_word)
                    pfile_word.save()
                except (ObjectDoesNotExist, Word.DoesNotExist):
                    pfile_word = Pfile(data=word)
                    pfile_word.save()
                    pfile_word.words.add(new_word)

    def check_if_url_exists(url):
        return Article.objects.filter(url=url).exists()

search/views/IndexView.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'search/index.html'


class HelpView(TemplateView):
    template_name = 'search/help.html'

search/views/ManageView.py
from search.models import Article, Postingfile
from django.views import generic
from django.shortcuts import render
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Count


class ManageView(generic.TemplateView):
    template_name = 'manage/index.html'


class ManageFilesView(generic.TemplateView):
    template_name = 'manage/manage-articles.html'


class ManageStoplistView(generic.TemplateView):
    template_name = 'manage/manage-stoplist.html'



class SettingsView(generic.TemplateView):
    template_name = 'manage/manage-settings.html'


class PostingfileView(generic.ListView):
    model = Postingfile
    template_name = 'manage/postingfile.html'
    context_object_name = 'results'

    def get_queryset(self):
        return Postingfile.objects.all().annotate(num_articles=Count('words')) \
                .order_by('-num_articles', 'data')


class ChangeFilesView(generic.ListView):
    model = Article
    template_name = 'manage/change_articles.html'
    context_object_name = "all_articles"

    def post(self, request):
        vis = request.POST.get('vis', "False")
        id = int(request.POST.get('article_id', "4"))
        print(id)
        print(vis)
        error = ["ok"]

        try:
            article = Article.objects.get(pk=id)
            article.hide = eval(vis)
            article.save()
        except ObjectDoesNotExist:
            error ="Either the entry or blog doesn't exist."

        return render(request, self.template_name, {'all_articles': Article.objects.all(), "error":error})


class DeleteFilesView(generic.TemplateView):
    template_name = 'manage/submit.html'
    context_object_name = 'result'

    def get_context_data(self, **kwargs):
        context = super(DeleteFilesView, self).get_context_data(**kwargs)
        Article.objects.filter(hide=True).delete()
        Postingfile.objects.filter(words__isnull=True).delete()
        context['result'] = "Hidden articles were deleted"
        return context

search/templates/search/Stoplist_form.html
{%extends 'search/base.html' %}
{%block title%}Stoplist Manager{%endblock%}
{% load staticfiles %}

{% block body %}
<button id="go-back" class="btn btn-warning">Back</button>
<h1>Add Word To Stoplist</h1>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'manage/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </div>
</form>

{% endblock %}

search/templates/search/advance.html
{%extends 'search/base.html' %}

{%block title%}Advance Search{%endblock%}
{% block body %}

<h1>Advance Search</h1>

{% if error_message %}
    <p><pre>{{error_message}}</pre></p>
{% endif %}
<div class="form">
    <form action="{%url 'search:advance-results' %}" method="post" class="form-group">
        {% csrf_token%}
        <div class="form-group form-group-sm">
            <div class="col-sm-2">
                <label for="find" class="control-label">search</label>
            </div>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="find" name="find" placeholder="search"><br>
            </div>
        </div>
        <div class="form-group form-group-sm">
            <div class="col-sm-2">
                <label for="smeth" class="control-label">add method</label>
            </div>
            <div class="col-sm-10">
                <button type="button" class="advance_meth btn" name="smeth" value="^">not</button>
                <button type="button" class="advance_meth btn" name="smeth" value="||">or</button>
                <button type="button" class="advance_meth btn" name="smeth" value="&&">and</button>
                <button type="button" class="advance_meth btn" name="smeth" value="&">easy and</button>
            </div>
        </div>
        <div class="form-group form-group-sm">
             <div class="col-sm-2">
                 <label for="sound">soundex</label>
             </div>
             <div class="col-sm-10">
                 <input type="checkbox" value="yes" name="sound">
             </div>
        </div>
        <div class="col-sm-2 button">
            <input value="submit" name="submit" type="submit" class="btn">
        </div>
    </form>
</div>
<div class="advance col-sm-12">
    <a href="{% url 'search:index'%}">Regular Search</a>
</div>
{% endblock %}

search/templates/search/article_form.html
{%extends 'search/base.html' %}
{%block title%}Add New Files{%endblock%}

{% block body %}
<button id="go-back">Back</button>

<h3>Add Files</h3>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'manage/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </div>
</form>
{% endblock %}

search/templates/search/article_list.html
{%extends 'search/base.html' %}
{%block title%}Articles{%endblock%}

{% block body %}
<button id="go-back" class="btn btn-warning">Back</button>
{% if all_articles %}
<h3>All Articles</h3>
    {% for article in all_articles %}
    <div class="result">
        <h4><a href="{{article.get_url}}">{{article.get_title }}</a></h4>
        <p>
            <div class="link">{{article.get_url}}</div>
            <div class="summary">{{article.get_summary }}...</div>
        </p>
    </div>
    {% endfor %}
{% else %}
    <h3>{{error_msg}}</h3>
{% endif %}

{% endblock %}

search/templates/search/articles.html
{%extends 'search/base.html' %}
{%block title%}Articles{%endblock%}

{% block body %}
<button id="go-back">Back</button>
{% if all_articles %}
<h3>All Articles</h3>
    {% for article in all_articles %}
    <div>
        <h4><a href="{% url 'search:details' article.id %}">{{article.get_title }}</a></h4>
        <p>{{article.get_summary }}...</p>
    </div>
    {% endfor %}
{% else %}
    <h3>No Articles</h3>
{% endif %}

{% endblock %}

search/templates/search/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>{%block title%}Search Engine{%endblock%}</title>
     {% load staticfiles %}
    <link rel="stylesheet" href="{%static 'search/css/bootstrap.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <script src="{%static 'search/js/jquery.min.js' %}"></script>
    <script src="{%static 'search/js/bootstrap.min.js' %}" ></script>
    <link rel="stylesheet" href="{% static 'search/css/style.css' %}">
    <script src="{%static 'search/js/script.js' %}"></script>
    {% block scripts%}
    {%endblock%}
</head>
<body>
<div id="background"></div>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'search:index'%}">Search Articles</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'search:index'%}">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="{%url 'search:articles'%}">Articles</a></li>
        <li><a href="{%url 'search:advance-search'%}">Advance</a></li>
        <li><a href="{%url 'search:help'%}">Help</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'search:manage'%}">Manage</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block body %}
{% endblock %}
</body>
</html>

search/templates/search/detail.html
{%extends 'search/base.html' %}
{%block title%}Article Details{%endblock%}

{% block body %}
    <button id="go-back" class="btn btn-warning">Back</button>

    <h1>Title : {{article.get_title}}</h1>
    <h3>{{article.get_author}}</h3>
    <p>{{article.get_data}}</p>
{% endblock %}

search/templates/search/help.html
{%extends 'search/base.html' %}
{%block title%}Help{%endblock%}

{% block body %}
    <button id="go-back" class="btn btn-warning go-back rtl">Back</button>
    <div class="help_wrapper">

        <h2>Help</h2>
        <article>
            <h3>חיפוש רגיל</h3>
            <p>
            <ul>
                <li>
                    בחיפוש זה ניתן לבצע חיפושים פשוטים, בהן כל המילים יחופשו באותה השיטה בהתאם לבחירת המשתמש.
כל שעל המשתמש לעשות הוא להכניס משפט רגיל בשורת החיפוש, לבחור את אחת השיטות וללחוץ על כפתור ה-“Submit”.
(דוג' לחיפוש: hello world)
                </li>
            <li>
                שיטות קיימות:
                <ul>
                    <li>Or – יביא כל מאמר המכיל את אחת המילים לפחות שנכתבו בשורת החיפוש</li>
                    <li>And- יביא כל מאמר המכיל את כל המילים שנכתבו.</li>
                    <li>Easy and – יביא כל מאמר המכיל לפחות 60% מהמילים שנכתבו.</li>
                    <li>Not – יביא כל מאמר שאינו מכיל אף מילה שנכתבה (not or).</li>
                </ul>
            </li>
            <li>
                ישנה אפשרות לחפש מושגים דומים באמצעות סימון  ה-Soundex
            </li>
            </ul>
            </p>
        </article>
        <article>
            <h3>חיפוש מתקדם</h3>
            <p>
            <ul>
                <li>
בחיפוש זה ניתן לבצע חיפושים מתקדמים עם אופרטורים.
הכפתורים הם על מנת להקל בהוספת האופרטורים לסוף שורת החיפוש. ניתן להשתמש בהם אך אין זה חובה.
הערה: בחיפוש זה, חייבים לשים אופרטורים בין המילים. רווח לא יחשב כתו מפריד.
                    (דוג' לחיפוש: hello||word)
                </li>
            <li>שיטות החיפוש
                <ul>
                    <li>שיטת or - תסומן על ידי התווים ||</li>
                    <li>שיטת and - תסומן על ידי התווים &&</li>
                    <li>שיטת easy-and- תסומן על ידי התו &</li>
                    <li>שיטת not - תסומן על ידי התווים ( )^, או [ ]^ כאשר הביטוי בתוך סוגריים. לדוגמה, (and)^</li>
                </ul>
            </li>
            <li>ניתן ללחוץ על כפתורי השיטות כדי להוסיף את התו המבוקש לסוף שורת החיפוש.</li>
            <li>
            במקרה והוכנסו מספר שיטות בסוגריים או ללא סוגריים, תלקח רק השיטה הראשונה שנרשמה. על כן, יש להשתמש בסוגריים כדי להשתמש במספר שיטות.
            </li>
            <li>
ניתן לכתוב סוגריים בתוך סוגריים, אך רק זוג אחד בתוך זוג קיים. הסוגריים הראשונים יהיו מהסוג " (  )", בעוד שהסוגריים השניים ויהיו מהסוג "[  ]".

            </li>
            <li>
                ישנה אפשרות לחפש מושגים דומים באמצעות סימון  ה-Soundex
            </li>
            </ul>

            </p>
        </article>
    </div>
{% endblock %}

search/templates/search/index.html
{%extends 'search/base.html' %}

{%block title%}Home{%endblock%}
{% block body %}

<h1>HOME</h1>

{% if error_message %}
    <p><pre>{{error_message}}</pre></p>
{% endif %}

    <div class="form">
        <form action="{%url 'search:results' %}" method="post" class="form-group">
            {% csrf_token%}
            <div class="form-group form-group-sm">
                <div class="col-sm-2">
                    <label for="find" class="control-label">search</label>
                </div>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="find" name="find" placeholder="search"><br>
                </div>
            </div>
            <div class="form-group form-group-sm">
                <div class="col-sm-2">
                    <label for="smeth" class="control-label">choose method</label>
                </div>
                <div class="col-sm-10">
                     <input type="radio" class="smeth" name="smeth" value="or" checked><label class="control-label">or</label>
                    <input type="radio" class="smeth" name="smeth" value="and"><label class="control-label">and</label>
                    <input type="radio" class="smeth" name="smeth" value="easy-and"><label class="control-label">easy and</label>
                    <input type="radio" class="smeth" name="smeth" value="not"><label class="control-label">not</label>
                </div>
            </div>
            <div class="form-group form-group-sm">
                <div class="col-sm-2">
                    <label for="sound">soundex</label>
                </div>
                <div class="col-sm-10">
                    <input type="checkbox" value="yes" name="sound">
                </div>
            </div>
            <div class="col-sm-2 button">
                <input value="submit" name="submit" type="submit" class="btn">
            </div>
        </form>
    </div>
    <div class="col-sm-12 advance">
        <a href="{% url 'search:advance-search'%}">Advance Search</a>
    </div>
{% endblock %}

search/templates/search/results.html
{%extends 'search/base.html' %}
{%block title%}Results{%endblock%}
{% load staticfiles %}

{%block scripts%}
<script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.4.0/jquery.mark.min.js"></script>
<script>
        var words = {{keywords|safe}};
</script>
{%endblock%}

{% block body %}
<button id="go-back" class="btn btn-warning">Back</button>
<div class="wrapper">
    <h1>Results</h1>
    {%if not results%}
    <p>No Results</p>
    {%elif error%}
        <p>{{error}}</p>
    {%else%}
    <p class="sum">Results for: {{search}}. Number of results: {{results|length}}.</p>
    <article id="inputText">
        {%for article in results%}
        <h4><a href="{{article.get_url}}">{{article.get_title }}</a></h4>
            <p>
                <div class="link">{{article.get_url}}</div>
                <div class="summary">{{article.get_summary }}...</div>
            </p>
            <p class="print">
                <button class="send-print btn" onclick="printFile('{{article.url}}')">Print</button>
            </p>
          {%endfor%}
    </article>
    {%endif%}

    <div class="searched">
        <h4>Previous Searching</h4>
        {%if searcher%}
        <ul>
            {%for search in searcher%}
            <li>{{search}}</li>
            {%endfor%}
        </ul>
        {%else%}
            No Previous Searches
        {%endif%}
    </div>

</div>

{% endblock %}